language: node_js
sudo: false
node_js:
  - "8.3"

install:
  - npm install -g yarn
  - yarn install

script:
    #Master
  - if [ $TRAVIS_BRANCH == "master" ]; then
      yarn delivery:prod;
    fi

    #Develop
  - if [ $TRAVIS_BRANCH == "develop" ]; then
      yarn delivery:prod;
    fi

# whitelist
branches:
  only:
  - master
  - develop
