language: node_js
sudo: false
node_js:
  - "8.3"

install:
  - npm install -g yarn
  - yarn install

script:
    #Fake Build
  - yarn build:prod

    #Master
  - if [ $TRAVIS_BRANCH == "master" ]; then
      yarn uploadTo:prod;
    fi

    #Develop
  - if [ $TRAVIS_BRANCH == "develop" ]; then
      yarn uploadTo:prod;
    fi
