language: node_js
sudo: false
node_js:
  - "8.3"

install:
  - npm i

script:
    #Fake Build
  - npm run build:prod

    #Master
  - if [ $TRAVIS_BRANCH == "master" ]; then
      npm run uploadTo:prod;
    fi

    #Develop
#  - if [ $TRAVIS_BRANCH == "develop" ]; then
#      npm run uploadTo:prod;
#    fi
